# Generated by Django 5.1 on 2024-09-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='incident_reports/'),
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='rules',
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('closed', 'Closed'), ('archived', 'Archived')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='type',
            field=models.CharField(choices=[('security_incident', 'Security Incident'), ('network_traffic', 'Network Traffic'), ('user_activity', 'User Activity'), ('system_performance', 'System Performance'), ('compliance_audit', 'Compliance Audit')], max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='rules',
            field=models.ManyToManyField(blank=True, related_name='incident_reports', to='core.rule'),
        ),
    ]
