# Generated by Django 5.1.1 on 2024-09-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_incidentreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
