
version: '1.2'

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "${DOCKER_FRONTEND_PORT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:3000/api}
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "${DOCKER_BACKEND_PORT:-8000}:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG:-True}
      - DB_NAME=${DB_NAME:-siem_db}
      - DB_USER=${DB_USER:-siem_user}
      - DB_PASSWORD=${DB_PASSWORD:-random_password}
      - DB_HOST=db
      - DB_PORT=3306
    command: sh -c "while ! nc -z db 3306; do sleep 1; done; python manage.py runserver_plus --print-sql 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: mariadb:10.5
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-siem_db}
      - MYSQL_USER=${DB_USER:-siem_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-random_password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-random_password}
    ports:
      - "${DOCKER_DB_PORT:-3307}:3306"

volumes:
  mariadb_data: