FROM python:3.12

WORKDIR /backend

RUN apt-get update && apt-get install -y

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "siem", "worker", "-l", "info"]