FROM python:3.12

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/

# Create log_files directory
RUN mkdir /log_files

CMD ["sh", "-c", "python manage.py migrate && python manage.py start_log_watcher & python manage.py runserver 0.0.0.0:8000"]