FROM python:3.12


WORKDIR /backend

COPY requirements.txt /backend/
RUN pip install -r requirements.txt

COPY . .


CMD ["sh", "-c", "python manage.py migrate && python manage.py start_log_watcher & python manage.py runserver 0.0.0.0:8000"]