# Generated by Django 4.2.14 on 2024-08-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeEventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_time', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('severity_value', models.IntegerField()),
                ('severity', models.CharField(max_length=255)),
                ('event_id', models.IntegerField()),
                ('source_name', models.CharField(max_length=255)),
                ('provider_guid', models.CharField(max_length=255)),
                ('version', models.IntegerField()),
                ('task', models.IntegerField()),
                ('opcode_value', models.IntegerField()),
                ('record_number', models.IntegerField()),
                ('process_id', models.IntegerField()),
                ('thread_id', models.IntegerField()),
                ('channel', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('account_type', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('opcode', models.CharField(max_length=255)),
                ('event_received_time', models.CharField(max_length=255)),
                ('source_module_name', models.CharField(max_length=255)),
                ('source_module_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rule')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.bronzeeventdata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
