# Generated by Django 5.1 on 2024-09-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeEventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('h_version', models.IntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('iso_timestamp', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('process_id', models.CharField(blank=True, max_length=50, null=True)),
                ('Keywords', models.CharField(blank=True, max_length=50, null=True)),
                ('EventType', models.CharField(blank=True, max_length=50, null=True)),
                ('EventID', models.CharField(blank=True, max_length=50, null=True)),
                ('ProviderGuid', models.CharField(blank=True, max_length=255, null=True)),
                ('Version', models.CharField(blank=True, max_length=10, null=True)),
                ('Task', models.CharField(blank=True, max_length=10, null=True)),
                ('OpcodeValue', models.CharField(blank=True, max_length=10, null=True)),
                ('RecordNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('ActivityID', models.CharField(blank=True, max_length=255, null=True)),
                ('ThreadID', models.CharField(blank=True, max_length=50, null=True)),
                ('Channel', models.CharField(blank=True, max_length=255, null=True)),
                ('Domain', models.CharField(blank=True, max_length=255, null=True)),
                ('AccountName', models.CharField(blank=True, max_length=255, null=True)),
                ('UserID', models.CharField(blank=True, max_length=50, null=True)),
                ('AccountType', models.CharField(blank=True, max_length=50, null=True)),
                ('Opcode', models.CharField(blank=True, max_length=100, null=True)),
                ('PackageName', models.CharField(blank=True, max_length=255, null=True)),
                ('ContainerId', models.CharField(blank=True, max_length=255, null=True)),
                ('EventReceivedTime', models.DateTimeField(blank=True, null=True)),
                ('SourceModuleName', models.CharField(blank=True, max_length=50, null=True)),
                ('SourceModuleType', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('extra_fields', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('date_time', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('process', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
