# Generated by Django 5.1 on 2024-09-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='processed',
        ),
    ]
