# Generated by Django 4.2.15 on 2024-08-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_bronzeeventdata_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzeeventdata',
            name='app_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='context_info1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='context_info2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='context_info3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='context_type1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='context_type2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='context_type3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='event_received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='execution_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='nxlog_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='opcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='opcode_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='operation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='operation_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='operation_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='process_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='provider_guid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='queued_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='record_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='sla_threshold_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='source_module_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='source_module_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='task',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
