# Generated by Django 4.2.15 on 2024-08-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_bronzeeventdata_app_name_bronzeeventdata_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='context_info1',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='context_info2',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='context_info3',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='context_type1',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='context_type2',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='context_type3',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='execution_time_ms',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='operation_id',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='operation_name',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='queued_time_ms',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='sla_threshold_ms',
        ),
    ]
