# Generated by Django 4.2.15 on 2024-08-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_remove_bronzeeventdata_context_info1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='event_received_time',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='message',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='nxlog_keywords',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='opcode',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='opcode_value',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='process_id',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='provider_guid',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='record_number',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='source_module_name',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='source_module_type',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='task',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='bronzeeventdata',
            name='version',
        ),
    ]
