# Generated by Django 4.2.15 on 2024-08-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_remove_bronzeeventdata_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzeeventdata',
            name='AccountName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='AccountType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='ActivityID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='Channel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='ContainerId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='Domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='EventID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='EventReceivedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='EventType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='Keywords',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='Opcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='OpcodeValue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='PackageName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='ProviderGuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='RecordNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='SourceModuleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='SourceModuleType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='Task',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='ThreadID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='UserID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='Version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='app_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='h_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='iso_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bronzeeventdata',
            name='process_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
