# Generated by Django 4.2.15 on 2024-08-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_bronzeeventdata_accountname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='EventReceivedTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='iso_timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
