# Generated by Django 4.2.15 on 2024-08-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_alter_bronzeeventdata_eventreceivedtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='OpcodeValue',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
