# Generated by Django 4.2.15 on 2024-08-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_bronzeeventdata_opcodevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='Opcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='OpcodeValue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
