# Generated by Django 4.2.15 on 2024-08-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0010_alter_bronzeeventdata_opcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzeeventdata',
            name='extra_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
