# Generated by Django 5.1 on 2024-08-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0012_routerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerdata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='routerdata',
            name='date_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
