# Generated by Django 5.1 on 2024-08-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_remove_routerdata_timestamp_routerdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bronzeeventdata',
            name='iso_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
