# Generated by Django 5.1 on 2024-08-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0013_remove_routerdata_timestamp_routerdata_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzeeventdata',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
