# Generated by Django 5.1 on 2024-08-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0014_bronzeeventdata_processed'),
        ('logs', '0015_alter_bronzeeventdata_eventreceivedtime'),
    ]

    operations = [
    ]
