# Generated by Django 4.2.14 on 2024-08-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('conditions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
