# Generated by Django 5.1.1 on 2024-09-25 01:26

from django.db import migrations

def grant_permissions(apps, schema_editor):
    # SQL command to grant all privileges to 'siem_user' on 'test_siem_db'
    schema_editor.execute("GRANT ALL PRIVILEGES ON test_siem_db.* TO 'siem_user'@'%';")
    schema_editor.execute("FLUSH PRIVILEGES;")

class Migration(migrations.Migration):

    dependencies = [
        # Replace with the last migration file in the core app
        ('core', '0001_initial'),  # Change this to the actual last migration file if different
    ]

    operations = [
        migrations.RunPython(grant_permissions),
    ]
